### ISSUE TITLE
TextStyle changes from parents are lost

### ISSUE THREAD

**Issue by Erfa** [Cretezy/flutter_linkify#27]
I noticed that if you have a TextStyle as a parent Widget to Linkify, that styling is overriden by whatever style you set in Linkify.

Here's an example:
```dart
DefaultTextStyle.merge(
  style: TextStyle(decoration: TextDecoration.lineThrough),
  child: Linkify(
    text: 'Testing https://github.com',
  ),
)
```

This will correctly identify the link, but it will lose the `TextDecoration.lineThrough` defined by the parent. Seems like the desired behavior would be to merge them? I'm fairly new to Flutter so I'm not sure if it's possible.

**Comment by Cretezy** [comment]
This is due to `DefaultTextStyle` not overriding `body1`.

Doing this does fix it:

```dart
Theme(
  data: ThemeData(
    textTheme: TextTheme(
      body1: TextStyle(decoration: TextDecoration.lineThrough),
    ),
  ),
  child: Linkify(
    text: 'Testing https://github.com',
  ),
)
```

Doing does the same but is much simpler:

```dart
Linkify(
  text: 'Testing https://github.com',
  style: TextStyle(decoration: TextDecoration.lineThrough),
)
```

![image](https://user-images.githubusercontent.com/2672503/71529837-ca364500-28b4-11ea-8378-194f3bbbf995.png)


To change the link to also have `lineThrough`, pass it in the `linkStyle`:

```dart
Linkify(
  text: 'Testing https://github.com',
  style: TextStyle(decoration: TextDecoration.lineThrough),
  linkStyle: TextStyle(
    decoration: TextDecoration.combine(
      [TextDecoration.lineThrough, TextDecoration.underline],
    ),
  ),
)
```

![image](https://user-images.githubusercontent.com/2672503/71529885-15e8ee80-28b5-11ea-8e73-fe11e3b7ecc4.png)
